# frozen_string_literal: true

module DevEnv
  # The on-disk record of one environment: its state JSON, the environment
  # file its service runs with, and the generated launcher script.
  class Store
    include Util

    def initialize(state_dir:, run_dir:)
      @state_dir = state_dir
      @run_dir = run_dir
    end

    def state_path(key) = File.join(@state_dir, "#{key}.json")
    def env_path(key)   = File.join(@state_dir, "#{key}.env")
    def run_path(key)   = File.join(@run_dir, "#{key}.sh")

    def exist?(key) = File.exist?(state_path(key))

    def keys = Dir.glob(File.join(@state_dir, "*.json")).map { |f| File.basename(f, ".json") }.sort

    # A lifecycle operation may remove an unrelated environment after globbing
    # but before it is read. Atomic writes guarantee complete JSON; disappearing
    # files are simply absent from this snapshot.
    def states
      Dir.glob(File.join(@state_dir, "*.json")).sort.filter_map do |path|
        JSON.parse(File.read(path))
      rescue Errno::ENOENT
        nil
      end
    end

    def load(key)
      raise Error, "no environment #{key.inspect} (try: dev-env list)" unless exist?(key)
      JSON.parse(File.read(state_path(key)))
    end

    def save(key, state) = atomic_write(state_path(key), JSON.pretty_generate(state) + "\n")

    def write_env(key, env) = atomic_write(env_path(key), env.map { |k, v| "#{k}=#{v}" }.join("\n") + "\n")

    # The same environment the service runs with, so `after_down` hooks and
    # summary commands see exactly what the server sees.
    def saved_env(key)
      raise Error, "no environment file for #{key.inspect} — bring it up first" unless File.exist?(env_path(key))
      File.readlines(env_path(key), chomp: true).reject(&:empty?).to_h { |line| line.split("=", 2) }
    end

    # A launcher per environment: it holds the project's own server command,
    # which the shared systemd template unit cannot express.
    def write_launcher(key, worktree, server)
      atomic_write(run_path(key), <<~SH, mode: 0o755)
        #!/bin/sh
        # Generated by dev-env — regenerated on every `up`.
        cd #{worktree} || exit 1
        exec #{server}
      SH
    end

    def delete(key) = FileUtils.rm_f([state_path(key), env_path(key), run_path(key)])
  end
end
